/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VoxVoting } from './VoxVoting.js';
export * as factories from './factories/index.js';
export { VoxVoting__factory } from './factories/VoxVoting__factory.js';
