/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface VoxVotingInterface extends Interface {
    getFunction(nameOrSignature: "createPoll" | "getPoll" | "hasVoted" | "owner" | "pollCount" | "renounceOwnership" | "transferOwnership" | "vote"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "PollCreated" | "VoteCast"): EventFragment;

    encodeFunctionData(functionFragment: 'createPoll', values: [string, string[], BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPoll', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pollCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'createPoll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPoll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pollCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PollCreatedEvent {
      export type InputTuple = [pollId: BigNumberish, question: string, startsAt: BigNumberish, endsAt: BigNumberish, creator: AddressLike];
      export type OutputTuple = [pollId: bigint, question: string, startsAt: bigint, endsAt: bigint, creator: string];
      export interface OutputObject {pollId: bigint, question: string, startsAt: bigint, endsAt: bigint, creator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [pollId: BigNumberish, voter: AddressLike, optionId: BigNumberish];
      export type OutputTuple = [pollId: bigint, voter: string, optionId: bigint];
      export interface OutputObject {pollId: bigint, voter: string, optionId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface VoxVoting extends BaseContract {
    
    connect(runner?: ContractRunner | null): VoxVoting;
    waitForDeployment(): Promise<this>;

    interface: VoxVotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createPoll: TypedContractMethod<
      [question: string, options: string[], startsAt: BigNumberish, endsAt: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    getPoll: TypedContractMethod<
      [pollId: BigNumberish, ],
      [[string, bigint, bigint, bigint, string, string[], bigint[], boolean] & {question: string, startsAt: bigint, endsAt: bigint, totalVotes: bigint, creator: string, options: string[], voteCounts: bigint[], isActive: boolean }],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [pollId: BigNumberish, voter: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pollCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    vote: TypedContractMethod<
      [pollId: BigNumberish, optionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createPoll'): TypedContractMethod<
      [question: string, options: string[], startsAt: BigNumberish, endsAt: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPoll'): TypedContractMethod<
      [pollId: BigNumberish, ],
      [[string, bigint, bigint, bigint, string, string[], bigint[], boolean] & {question: string, startsAt: bigint, endsAt: bigint, totalVotes: bigint, creator: string, options: string[], voteCounts: bigint[], isActive: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [pollId: BigNumberish, voter: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pollCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [pollId: BigNumberish, optionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PollCreated'): TypedContractEvent<PollCreatedEvent.InputTuple, PollCreatedEvent.OutputTuple, PollCreatedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PollCreated(uint256,string,uint64,uint64,address)': TypedContractEvent<PollCreatedEvent.InputTuple, PollCreatedEvent.OutputTuple, PollCreatedEvent.OutputObject>;
      PollCreated: TypedContractEvent<PollCreatedEvent.InputTuple, PollCreatedEvent.OutputTuple, PollCreatedEvent.OutputObject>;
    

      'VoteCast(uint256,address,uint256)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    
    };
  }
